before_script:
  - npm install -g gulp-cli
  - npm install -g mocha
  - npm install gulp-mocha
script: gulp test
deploy:
  provider: heroku
  api_key: 99a4dc36-4fb7-4b3d-bb67-87b2842432fe
  app:
    master: tdcmioiio